/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginMagicLinkRouteImport } from './routes/login/magic-link'
import { Route as LoginForgotPasswordRouteImport } from './routes/login/forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedIncomesRouteImport } from './routes/_authenticated/incomes'
import { Route as AuthenticatedFutureLaunchesRouteImport } from './routes/_authenticated/future-launches'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedCardsRouteImport } from './routes/_authenticated/cards'
import { Route as AuthenticatedGoalsIndexRouteImport } from './routes/_authenticated/goals/index'
import { Route as AuthenticatedGoalsCreateRouteImport } from './routes/_authenticated/goals/create'
import { Route as AuthenticatedGoalsIdRouteImport } from './routes/_authenticated/goals/$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginMagicLinkRoute = LoginMagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => LoginRoute,
} as any)
const LoginForgotPasswordRoute = LoginForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => LoginRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncomesRoute = AuthenticatedIncomesRouteImport.update({
  id: '/incomes',
  path: '/incomes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFutureLaunchesRoute =
  AuthenticatedFutureLaunchesRouteImport.update({
    id: '/future-launches',
    path: '/future-launches',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCardsRoute = AuthenticatedCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoalsIndexRoute = AuthenticatedGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoalsCreateRoute =
  AuthenticatedGoalsCreateRouteImport.update({
    id: '/goals/create',
    path: '/goals/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGoalsIdRoute = AuthenticatedGoalsIdRouteImport.update({
  id: '/goals/$id',
  path: '/goals/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/cards': typeof AuthenticatedCardsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/future-launches': typeof AuthenticatedFutureLaunchesRoute
  '/incomes': typeof AuthenticatedIncomesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/login/forgot-password': typeof LoginForgotPasswordRoute
  '/login/magic-link': typeof LoginMagicLinkRoute
  '/goals/$id': typeof AuthenticatedGoalsIdRoute
  '/goals/create': typeof AuthenticatedGoalsCreateRoute
  '/goals': typeof AuthenticatedGoalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/cards': typeof AuthenticatedCardsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/future-launches': typeof AuthenticatedFutureLaunchesRoute
  '/incomes': typeof AuthenticatedIncomesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/login/forgot-password': typeof LoginForgotPasswordRoute
  '/login/magic-link': typeof LoginMagicLinkRoute
  '/goals/$id': typeof AuthenticatedGoalsIdRoute
  '/goals/create': typeof AuthenticatedGoalsCreateRoute
  '/goals': typeof AuthenticatedGoalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/cards': typeof AuthenticatedCardsRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/future-launches': typeof AuthenticatedFutureLaunchesRoute
  '/_authenticated/incomes': typeof AuthenticatedIncomesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/login/forgot-password': typeof LoginForgotPasswordRoute
  '/login/magic-link': typeof LoginMagicLinkRoute
  '/_authenticated/goals/$id': typeof AuthenticatedGoalsIdRoute
  '/_authenticated/goals/create': typeof AuthenticatedGoalsCreateRoute
  '/_authenticated/goals/': typeof AuthenticatedGoalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/cards'
    | '/categories'
    | '/dashboard'
    | '/expenses'
    | '/future-launches'
    | '/incomes'
    | '/settings'
    | '/transactions'
    | '/auth/callback'
    | '/login/forgot-password'
    | '/login/magic-link'
    | '/goals/$id'
    | '/goals/create'
    | '/goals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/cards'
    | '/categories'
    | '/dashboard'
    | '/expenses'
    | '/future-launches'
    | '/incomes'
    | '/settings'
    | '/transactions'
    | '/auth/callback'
    | '/login/forgot-password'
    | '/login/magic-link'
    | '/goals/$id'
    | '/goals/create'
    | '/goals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_authenticated/cards'
    | '/_authenticated/categories'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/future-launches'
    | '/_authenticated/incomes'
    | '/_authenticated/settings'
    | '/_authenticated/transactions'
    | '/auth/callback'
    | '/login/forgot-password'
    | '/login/magic-link'
    | '/_authenticated/goals/$id'
    | '/_authenticated/goals/create'
    | '/_authenticated/goals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/magic-link': {
      id: '/login/magic-link'
      path: '/magic-link'
      fullPath: '/login/magic-link'
      preLoaderRoute: typeof LoginMagicLinkRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/forgot-password': {
      id: '/login/forgot-password'
      path: '/forgot-password'
      fullPath: '/login/forgot-password'
      preLoaderRoute: typeof LoginForgotPasswordRouteImport
      parentRoute: typeof LoginRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incomes': {
      id: '/_authenticated/incomes'
      path: '/incomes'
      fullPath: '/incomes'
      preLoaderRoute: typeof AuthenticatedIncomesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/future-launches': {
      id: '/_authenticated/future-launches'
      path: '/future-launches'
      fullPath: '/future-launches'
      preLoaderRoute: typeof AuthenticatedFutureLaunchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cards': {
      id: '/_authenticated/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof AuthenticatedCardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals/': {
      id: '/_authenticated/goals/'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals/create': {
      id: '/_authenticated/goals/create'
      path: '/goals/create'
      fullPath: '/goals/create'
      preLoaderRoute: typeof AuthenticatedGoalsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals/$id': {
      id: '/_authenticated/goals/$id'
      path: '/goals/$id'
      fullPath: '/goals/$id'
      preLoaderRoute: typeof AuthenticatedGoalsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCardsRoute: typeof AuthenticatedCardsRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFutureLaunchesRoute: typeof AuthenticatedFutureLaunchesRoute
  AuthenticatedIncomesRoute: typeof AuthenticatedIncomesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedGoalsIdRoute: typeof AuthenticatedGoalsIdRoute
  AuthenticatedGoalsCreateRoute: typeof AuthenticatedGoalsCreateRoute
  AuthenticatedGoalsIndexRoute: typeof AuthenticatedGoalsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCardsRoute: AuthenticatedCardsRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFutureLaunchesRoute: AuthenticatedFutureLaunchesRoute,
  AuthenticatedIncomesRoute: AuthenticatedIncomesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedGoalsIdRoute: AuthenticatedGoalsIdRoute,
  AuthenticatedGoalsCreateRoute: AuthenticatedGoalsCreateRoute,
  AuthenticatedGoalsIndexRoute: AuthenticatedGoalsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LoginRouteChildren {
  LoginForgotPasswordRoute: typeof LoginForgotPasswordRoute
  LoginMagicLinkRoute: typeof LoginMagicLinkRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginForgotPasswordRoute: LoginForgotPasswordRoute,
  LoginMagicLinkRoute: LoginMagicLinkRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
